export const ANOMALY_TYPES = {
  stampeder: {
    id: 'stampeder',
    name: 'Stampeder Anomaly',
    hp: 40, maxHp: 40,
    speed: 7.0,
    damage: 12,
    senseRadius: 18,
    attackCooldown: 1.0,
    attackRange: 1.8,
    corruptionAffinity: 10,
    color: '#ff3344',
    emissiveColor: '#ff0022',
    scale: [0.6, 1.2, 0.6],
    description: 'A manifestation of unthrottled cache stampede requests. Weak alone, deadly in waves.',
    mission: 'cacheStampede',
    isBoss: false,
  },
  siegeDrone: {
    id: 'siegeDrone',
    name: 'Siege Drone',
    hp: 75, maxHp: 75,
    speed: 3.5,
    damage: 20,
    senseRadius: 25,
    attackCooldown: 2.5,
    attackRange: 12.0,
    telegraphTime: 0.8,
    corruptionAffinity: 25,
    color: '#ffaa00',
    emissiveColor: '#ff6600',
    scale: [0.9, 0.9, 0.9],
    description: 'Fires high-frequency burst traffic. Telegraphed attacks can be mitigated with ZSET rate limits.',
    mission: 'rateLimitSiege',
    isBoss: false,
  },
  sludgeBlob: {
    id: 'sludgeBlob',
    name: 'Memory Sludge',
    hp: 120, maxHp: 120,
    speed: 2.0,
    damage: 15,
    senseRadius: 15,
    attackCooldown: 1.8,
    attackRange: 2.2,
    corruptionAffinity: 50,
    canSplit: true,
    splitThreshold: 60,
    color: '#8800ff',
    emissiveColor: '#aa00ff',
    scale: [1.4, 1.0, 1.4],
    description: 'Leaked RAM rendered corporeal. Splits when taking heavy non-UNLINK damage and thrives in corruption.',
    mission: 'memoryLeakCrisis',
    isBoss: false,
  },
  phantomConsumer: {
    id: 'phantomConsumer',
    name: 'Phantom Consumer',
    hp: 90, maxHp: 90,
    speed: 5.0,
    damage: 18,
    senseRadius: 20,
    attackCooldown: 1.2,
    attackRange: 2.5,
    corruptionAffinity: 30,
    stealsUnacked: true,
    color: '#00e5ff',
    emissiveColor: '#0088ff',
    scale: [0.7, 1.6, 0.7],
    description: 'A dead-letter consumer stranded in pending state. Steals unacked stream messages.',
    mission: 'deadLetterPipeline',
    isBoss: false,
  },
  nullPointer: {
    id: 'nullPointer',
    name: 'NULL_POINTER',
    hp: 500, maxHp: 500,
    speed: 3.0,
    damage: 35,
    senseRadius: 40,
    attackCooldown: 2.0,
    attackRange: 5.0,
    corruptionAffinity: 100,
    color: '#ff0055',
    emissiveColor: '#cc0000',
    scale: [2.5, 3.5, 2.5],
    description: 'The master core anomaly causing split-brain cluster breakdown across the mega-datacenter.',
    mission: 'splitBrainFailover',
    isBoss: true,
    phases: [
      { phase: 1, hpThreshold: 0.66, name: 'Split-Brain Surge', attackBonus: 1.2 },
      { phase: 2, hpThreshold: 0.33, name: 'Failover Enrage', speedBonus: 1.4 },
      { phase: 3, hpThreshold: 0.0, name: 'Null State Overdrive', corruptionPulse: true },
    ],
  },
}

export function getAnomalyType(id) {
  return ANOMALY_TYPES[id] || ANOMALY_TYPES.stampeder
}