import React, { useEffect, useMemo, useRef, useState } from 'react'

// The console is the game's teaching surface, and it has to work for someone
// who has never typed a Redis command.
//
// Two ways in, both live at once (the Interaction Ladder, plan §8):
//   Tier 1 — click a suggested card. No typing, no syntax, no memory.
//   Tier 3 — type the command freely.
// Every card names the physical thing first and the real command second, so
// the player learns the vocabulary by seeing both attached to one action they
// chose on purpose.

// Suggestions are contextual: what this terminal teaches comes first.
const CARD_LIBRARY = {
  EXPIRE: {
    physical: 'Refresh your session',
    line: 'EXPIRE session:7742 90',
    teaches: 'EXPIRE key seconds — resets how long a key lives. This is your health bar.',
  },
  SETEX: {
    physical: 'Store something WITH a timer',
    line: 'SETEX cache:manifest 60 ok',
    teaches: 'SETEX key seconds value — writes a key that deletes itself. Cache entries should almost always have one.',
  },
  SET: {
    physical: 'Cache the answer',
    line: 'SET cache:manifest ok',
    teaches: 'SET key value — stores a value so the next read is instant instead of hitting the source.',
  },
  TTL_MARGIT: {
    physical: 'Put a timer on the orphaned ledger',
    line: 'EXPIRE margit:ledger 120',
    teaches: 'A key with no expiry never leaves on its own. EXPIRE gives it one.',
  },
  PTTL: {
    physical: 'Check your remaining time',
    line: 'PTTL session:7742',
    teaches: 'PTTL key — milliseconds of life left. TTL gives the same answer in seconds.',
  },
  MEMORY: {
    physical: 'Ask how full the room is',
    line: 'INFO memory',
    teaches: 'When memory fills, Redis starts evicting keys. THE EVICTOR moves faster the fuller it gets.',
  },
  KEYS: {
    physical: 'List everything (slow — careful)',
    line: 'SCAN 0',
    teaches: 'SCAN walks the keyspace in small batches. KEYS * does it all at once and freezes production.',
  },
}

const DEFAULT_CARDS = ['EXPIRE', 'PTTL', 'SET', 'MEMORY']

export default function CommandConsole({ open, onClose, onSubmit, terminal, history }) {
  const [text, setText] = useState('')
  const [selected, setSelected] = useState(0)
  const inputRef = useRef(null)

  const cards = useMemo(() => {
    const ids = []
    if (terminal) {
      if (terminal.teaches === 'EXPIRE') ids.push('EXPIRE', 'PTTL', 'TTL_MARGIT')
      else if (terminal.teaches === 'SETEX') ids.push('SETEX', 'TTL_MARGIT', 'MEMORY')
      else if (terminal.teaches === 'SET') ids.push('SET', 'SETEX', 'KEYS')
    }
    for (const id of DEFAULT_CARDS) if (!ids.includes(id)) ids.push(id)
    return ids.map((id) => ({ id, ...CARD_LIBRARY[id] })).filter((c) => c.line)
  }, [terminal])

  useEffect(() => {
    if (open && inputRef.current) inputRef.current.focus()
    if (!open) setText('')
  }, [open])

  if (!open) return null

  function fire(line) {
    const trimmed = String(line || '').trim()
    if (!trimmed) return
    onSubmit(trimmed)
    setText('')
  }

  function onKeyDown(e) {
    // Stop movement keys reaching the player controller while typing.
    e.stopPropagation()
    if (e.key === 'Enter') { fire(text); return }
    if (e.key === 'Escape') { onClose(); return }
    if (e.key === 'Tab') {
      e.preventDefault()
      const next = (selected + 1) % cards.length
      setSelected(next)
      setText(cards[next].line)
    }
  }

  return (
    <div
      data-testid="command-console"
      className="pointer-events-auto absolute inset-x-0 bottom-0 border-t border-[#4fd8ff]/30 p-5 font-mono backdrop-blur-sm"
      // Set as an inline colour rather than a Tailwind opacity utility: the
      // console must stay readable over a blown-out emissive terminal screen,
      // and only the /5-step opacities are generated by default.
      style={{ backgroundColor: 'rgba(3,6,10,0.97)' }}
      onKeyDown={onKeyDown}
    >
      <div className="mx-auto max-w-5xl">
        <div className="mb-3 flex items-center justify-between">
          <span className="text-[10px] tracking-[0.35em] text-[#4fd8ff]">
            {terminal ? terminal.label : 'FIELD CONSOLE'}
          </span>
          <span className="text-[10px] text-white/35">
            ENTER run · TAB cycle · ESC close
          </span>
        </div>

        {terminal && (
          <div className="mb-3 text-xs text-white/60">{terminal.prompt}</div>
        )}

        {/* Tier 1: no typing required. */}
        <div className="mb-4 grid grid-cols-2 gap-2 lg:grid-cols-4">
          {cards.map((c, i) => (
            <button
              key={c.id}
              type="button"
              onClick={() => fire(c.line)}
              onMouseEnter={() => setSelected(i)}
              className={`rounded border p-2 text-left transition-colors ${
                i === selected
                  ? 'border-[#4fd8ff]/70 bg-[#4fd8ff]/10'
                  : 'border-white/15 hover:border-white/35'
              }`}
            >
              <div className="text-[11px] text-white/90">{c.physical}</div>
              <div className="mt-1 truncate text-[10px] text-[#4fd8ff]/80">{c.line}</div>
            </button>
          ))}
        </div>

        {/* What the highlighted card actually teaches. */}
        {cards[selected] && (
          <div className="mb-3 border-l-2 border-[#4fd8ff]/40 pl-3 text-[11px] leading-relaxed text-white/55">
            {cards[selected].teaches}
          </div>
        )}

        {/* Tier 3: free typing. */}
        <div className="flex items-center gap-2 border border-white/20 bg-black/70 px-3 py-2">
          <span className="text-[#6effc0]">&gt;</span>
          <input
            ref={inputRef}
            value={text}
            onChange={(e) => setText(e.target.value)}
            spellCheck={false}
            autoComplete="off"
            placeholder="type a redis command…"
            className="flex-1 bg-transparent text-sm text-white outline-none placeholder:text-white/25"
          />
        </div>

        {/* Recent results. */}
        <div className="mt-3 max-h-24 overflow-y-auto text-[11px]">
          {(history || []).slice(-5).reverse().map((h, i) => (
            <div key={history.length - i} className="flex gap-3 py-0.5">
              <span className="text-white/35">{h.line}</span>
              <span style={{ color: h.ok ? '#6effc0' : '#ff6b6b' }}>{h.text}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

export { CARD_LIBRARY }
